name: .NET Core CI

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up .NET Core SDK
      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'  # Specify your .NET version here

      # Step 3: Restore dependencies (if any)
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: dotnet build

      # Step 5: Run tests (if applicable)
      - name: Run tests
        run: dotnet test
